import os
import shutil
import subprocess
import tempfile
from collections.abc import Callable, Coroutine
from dataclasses import dataclass, field
from logging import Logger
from multiprocessing import Process
from typing import ClassVar

from setup.conf import expand
from setup.job import Job
from setup.managers.manager import Manager, mark_resource
from setup.output import print_grid


@dataclass
class LocalConfig(Manager):
    desired: ClassVar[list["LocalConfig"]] = []
    name: str
    path: str
    files: list[str] = field(default_factory=list)
    comment_str: str = ""
    generated_output: str = ""
    state: tuple[bool, str] = (False, "")

    def __post_init__(self) -> None:
        mark_resource(self.name)
        self.desired.append(self)

    async def _set_status(self) -> None:
        path = expand(self.path)
        if not os.path.exists(path):
            self.state = (False, "MISSING")
            return
        with open(path, encoding="utf-8") as f:
            current_file = f.read()
            if current_file != self.generate_file_contents():
                self.state = (False, "NONMATCHING")
                return
        self.state = (True, "MATCHING")

    @classmethod
    def desired_printout(cls) -> str:
        lines = []
        for conf in sorted(cls.desired, key=lambda c: c.name):
            lines.append((conf.name,))
        return print_grid(("LOCAL CONFIG",), lines)

    @classmethod
    def status_printout(cls, show_all: bool) -> str:
        lines = []
        for conf in sorted(cls.desired, key=lambda c: c.name):
            if not show_all and conf.state[0]:
                continue
            lines.append((conf.name, (conf.state[1], conf.state[0])))
        return print_grid(("LOCAL CONFIG", "STATUS"), lines)

    def create_job(self) -> Job:
        return Job(
            name=self.name,
            description=f"Generate local config at {self.path}",
            job=self.write_file(),
        )

    def generate_file_contents(self) -> str:
        if self.generated_output:
            return self.generated_output

        comment_str = self.comment_str or "#"
        header = f"""{comment_str} DO NOT MODIFY!
{comment_str} This file was automatically generated by mysetup. Manual changes
{comment_str} will be overridden on the next call to mysetup.
{comment_str}
{comment_str} This file was built from the following parts:
"""
        file_list = ""
        contents = ""
        for part_file in self.files:
            file_list += f"{comment_str}    * {part_file}\n"
            with open(expand(part_file), encoding="utf-8") as f:
                contents += f"{comment_str} {part_file}\n"
                contents += f.read()

        file_list += f"{comment_str}\n"
        self.generated_output = header + file_list + contents
        return self.generated_output

    def write_file(self) -> Callable[[Logger], Coroutine[None, None, bool]]:
        async def inner(logger: Logger) -> bool:
            logger.info(f"Generating local config at {self.path}")
            try:
                content = self.generate_file_contents()
            except FileNotFoundError as e:
                logger.error(
                    f"Failed to generate config {self.path} because {e.filename} was not found"
                )
                return False
            with open(expand(self.path), "w", encoding="utf-8") as f:
                f.write(content)
            return True

        return inner

    def print_diff(self) -> None:
        with open(expand(self.path), encoding="utf-8") as f:
            existing_contents = f.read()
        new_contents = self.generate_file_contents()

        with tempfile.TemporaryDirectory() as tmp:
            old_pipe = os.path.join(tmp, "existing")
            new_pipe = os.path.join(tmp, "new")

            def pipe_data(filename, content):
                os.mkfifo(filename)

                with open(filename, "w", encoding="utf-8") as f:
                    f.write(content)

            p1 = Process(target=pipe_data, args=(old_pipe, existing_contents))
            p2 = Process(target=pipe_data, args=(new_pipe, new_contents))

            p1.start()
            p2.start()

            args = [
                "delta",
                "--side-by-side",
                f"--width={shutil.get_terminal_size().columns}",
                old_pipe,
                new_pipe,
            ]
            r = subprocess.run(
                args, capture_output=True, text=True, check=False
            )

            p1.join()
            p2.join()
            print("\n".join(r.stdout.split("\n")[4:]))
