#! /usr/bin/env bash
if [[ -f /proc/sys/fs/binfmt_misc/WSLInterop ]]; then
    # https://github.com/microsoft/WSL/issues/11047#issuecomment-2663905431
    iconv -f utf8 -t utf16le | clip.exe
elif command -v xclip &> /dev/null; then
    xclip -sel clipboard
fi
    
