[tool.ruff]
line-length = 100
preview = true

[tool.ruff.lint]
select = [
    # pycodestyle and Pyflakes
    "W", "E", "F", 
    # isort
    "I", 
    # McCabe
    "C", 
    # Pylint
    "PLC", "PLE", "PLR", "PLW"]

[tool.ruff.lint.mccabe]
max-complexity = 15
